add_newline = true
command_timeout = 600
format = "$username$hostname$directory$git_branch$git_status$nix_shell$status[> ](bold green)"
right_format = "$cmd_duration"
scan_timeout = 10

[cmd_duration]
format = "[$duration]($style)"
min_time = 0
style = "bold yellow"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " "
read_only_style = "bold red"
style = "bold cyan"
truncate_to_repo = true
truncation_length = 5
truncation_symbol = ""

[git_status]
ahead = "⇡"
behind = "⇣"
conflicted = ""
deleted = "X$count"
diverged = "⇕"
modified = "!$count"
renamed = ""
staged = "+$count"
stashed = "󰀼$count"
style = "bold yellow"
typechanged = ""
untracked = "?$count"
up_to_date = ""

[hostname]
format = "[$ssh_symbol$hostname]($style) in "
ssh_only = true
ssh_symbol = " "
style = "bold green"

[nix_shell]
style = "bold blue"
symbol = " "

[status]
disabled = false
format = "[$symbol]($style)"
map_symbol = true
not_found_symbol = "󰍉 "
sigint_symbol = " "
signal_symbol = "󱑽 "
style = "bold red"
success_symbol = ""
symbol = "✗ "

[username]
format = "[$user]($style) in "
show_always = false
style_root = "red bold"
style_user = "blue bold"
